language: node_js
node_js:
  - "10.16.3"
branches:
  only:
  - master
warnings_are_errors: false
script:
  - npm install
  - npm run lint
  # - npm run test
  - npm run build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN