language: node_js
node_js:
  - "10"
cache:
  directories:
    - 'node_modules'
branches:
  only:
  - master
warnings_are_errors: false
script:
  - npm install
  # - npm run lint
  # - npm run test
  - unset CI
  - npm run build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN